global using System;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using Microsoft.Xna.Framework.Audio;
global using MamacitaOrbit.Objects.Interfaces;
global using MamacitaOrbit.Main.enums;
global using MamacitaOrbit.Main;
global using Microsoft.Xna.Framework.Content;